version: 0.1

phases:
  install:
    commands:
      - npm run globalize
      - npm install
  pre_build:
    commands:
      - npm run test
  build:
    commands:
      - webpack -d
  post_build:
    commands:
      - echo Nothing to do in the post_build phase
artifacts:
  files:
    - index.client
    - package.json
    - .ebextensions/*.config
    - public/*.html
    - public/client/*.client