version: 0.1

phases:
  install:
    commands:
      - echo Jared wuz here
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo No Build Stuff
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.js
    - package.json
    - .ebextensions/*.config
    - public/*.html
    - public/js/*.js
    - public/css/*.css