version: 0.1

phases:
  install:
    commands:
      - npm run globalize
      - npm install
  pre_build:
    commands:
      - echo npm run test
  build:
    commands:
      - webpack -d
  post_build:
    commands:
      - echo Nothing to do in the post_build phase
artifacts:
  files:
    - app/*.js
    - package.json
    - .ebextensions/*.config
    - public/*.html
    - public/css/*.css
    - public/js/*.js
    - public/img/*.ico
    - public/img/*.png
